---
---
- name: stop_perf-chart_service
  shell:
    stsd: service-control --stop vmware-perfcharts

- name: start_perf-chart_service
  shell:
    stsd: service-control --start vmware-perfcharts

    