---

- name: get dbcc_service state
  shell: "grep -i jndilookup {{ jar_file }} | wc -l"
  register: dbcc_output
  changed_when: false
  check_mode: false

- name: set check_varible
  set_fact:
    dbcc_service_vulnerable: "{{ dbcc_output.stdout | int }}"
  changed_when: false
  check_mode: false

- name: check for backup file
  stat:
    path: "{{ jar_file }}.bak"
  register: dbcc_backup_stat
  changed_when: false

- name: backup jar file
  copy:
    src: "{{ jar_file }}"
    dest: "{{ jar_file }}.bak"
    remote_src: yes
  when: dbcc_backup_stat.stat.exists == false

- name: Apply Fix
  command: zip -q -d {{ jar_file }} org/apache/logging/log4j/core/lookup/JndiLookup.class
  when: (dbcc_output.stdout | int) !=  0

- name: get dbcc_service state
  shell: "grep -i jndilookup {{ jar_file }}  | wc -l"
  register: dbcc_output
  changed_when: false
  when:  dbcc_service_vulnerable !=0
  check_mode: false

- name: validate its fixed
  assert:
    that: (dbcc_output.stdout | int) ==  0
    fail_msg: "fix did not work"
  when:  dbcc_service_vulnerable !=0
  check_mode: false