---
- name: get vum_service state
  shell: "java -jar start.jar --list-config"
  args:
    chdir:  /usr/lib/vmware-updatemgr/bin/jetty/
  register: vum_output
  changed_when: false

- name: set check_variable
  set_fact:
    vum_service_fixed: "{{ vum_output.stdout is search ('log4j2.formatMsgNoLookups = true') }}"
  changed_when: false
  
- name: check for backup file
  stat:
    path: "{{ base_file }}.bak"
  register: vum_backup_stat
  changed_when: false

- name: chuck a rod if already ran
  assert:
    that: vum_backup_stat.stat.exists == false
    fail_msg: "Backup exists, and the wrapper file is vulnerable"
    success_msg: "No previous backup"
  when: not vum_service_fixed

- name: backup wrapper file
  copy:
    src: "{{ base_file }}"
    dest: "{{ base_file }}.bak"
    remote_src: yes
  when:
    - not vum_service_fixed
    - vum_backup_stat.stat.exists == false
  
- name: update launch parameters for jvm
  lineinfile:
    path: "{{ base_file }}"
    insertafter: EOF
    line: -Dlog4j2.formatMsgNoLookups=true
  notify: 
    - restart_vum_service
  when:
    - not vum_service_fixed
    - vum_backup_stat.stat.exists == false

- name: kick the services over
  meta: flush_handlers

- name: get vum_service state
  shell: "java -jar start.jar --list-config"
  args:
    chdir:  /usr/lib/vmware-updatemgr/bin/jetty/
  register: vum_output
  changed_when: false

- name: validate its fixed
  assert:
    that: vum_output.stdout is search ('log4j2.formatMsgNoLookups = true')
    fail_msg: "fix did not work"
    success_msg: "Fix applied successfully"
  when: not vum_service_fixed
