---

- name: get cm_service strate
  shell: "grep -i jndilookup {{ jar_file }} | wc -l"
  register: cm_output
  changed_when: false

- name: set check_varible
  set_fact:
    cm_service_vulnerable: "{{ cm_output.stdout | int }}"
  changed_when: false

- name: check for backup file
  stat:
    path: "{{ jar_file }}.bak"
  register: cm_backup_stat
  changed_when: false

- name: backup jar file
  copy:
    src: "{{ jar_file }}"
    dest: "{{ jar_file }}.bak"
    remote_src: yes
  when: cm_backup_stat.stat.exists == false

- name: Apply Fix
  command: zip -q -d {{ jar_file }} org/apache/logging/log4j/core/lookup/JndiLookup.class
  when: (cm_output.stdout | int) !=  0
  notify: 
    - stop_cm_service
    - start_cm_service

- name: kick the services over
  meta: flush_handlers

- name: get cm_service strate
  shell: "grep -i jndilookup {{ jar_file }} | wc -l"
  register: cm_output
  changed_when: false
  when:  cm_service_vulnerable !=0

- name: validate its fixed
  assert:
    that: (cm_output.stdout | int) ==  0
    fail_msg: "fix did not work"
  when:  cm_service_vulnerable !=0
